"""AUTOGENERATED by tools/gen_queries.py — do not edit.

This file is generated from datasette_accounts/sql/queries.sql.
Regenerate with `just codegen-queries` after editing that file.
"""

from __future__ import annotations

import sqlite3
from dataclasses import dataclass
from typing import Any


@dataclass
class UserRow:
    id: str | None
    username: str
    password_hash: str
    is_admin: int
    disabled: int
    must_change_password: int
    failed_attempts: int
    locked_until: str | None
    created_at: str
    updated_at: str
    last_login_at: str | None
    expires_at: str | None
    pending_approval: int


@dataclass
class AdminStateRow:
    is_admin: int
    disabled: int


@dataclass
class SessionRow:
    token_sha256: str | None
    actor_id: str
    created_at: str
    expires_at: str
    last_seen_at: str
    user_agent: str | None
    ip: str | None


@dataclass
class IdentityRow:
    provider: str
    subject: str
    user_id: str
    email: str | None
    display_name: str | None
    created_at: str
    last_login_at: str | None


@dataclass
class CountIdentitiesByProviderRow:
    provider: str
    n: Any


@dataclass
class LoginAttemptRow:
    id: int | None
    username: str | None
    ip: str | None
    timestamp: str
    success: int
    reason: str | None


@dataclass
class AdminAuditRow:
    id: int | None
    timestamp: str
    operation: str
    actor_id: str | None
    target_id: str | None
    detail: str | None
    actor_username: str
    target_username: str


@dataclass
class ListAdminAuditOperationsRow:
    operation: str


@dataclass
class CapabilityGrantRow:
    action: str
    principal_type: str
    actor_id: str | None
    group_id: int | None


@dataclass
class SiteMessageRow:
    key: str | None
    body: str


@dataclass
class PasswordTokenRow:
    token_sha256: str | None
    user_id: str
    purpose: str
    created_at: str
    expires_at: str
    created_by: str | None
    username: str


@dataclass
class PasswordTokenMetaRow:
    user_id: str
    purpose: str
    created_at: str
    expires_at: str
    created_by: str | None
    created_by_username: str


def select_user_by_username(conn: sqlite3.Connection, username: str) -> UserRow | None:
    sql = """\
SELECT id, username, password_hash, is_admin, disabled, must_change_password,
       failed_attempts, locked_until, created_at, updated_at, last_login_at,
       expires_at, pending_approval
FROM datasette_accounts_users
WHERE username = $username::text;
"""
    params = {"username::text": username}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return UserRow(*row) if row is not None else None


def select_user_by_id(conn: sqlite3.Connection, user_id: str) -> UserRow | None:
    sql = """\
SELECT id, username, password_hash, is_admin, disabled, must_change_password,
       failed_attempts, locked_until, created_at, updated_at, last_login_at,
       expires_at, pending_approval
FROM datasette_accounts_users
WHERE id = $user_id::text;
"""
    params = {"user_id::text": user_id}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return UserRow(*row) if row is not None else None


def list_users(conn: sqlite3.Connection) -> list[UserRow]:
    sql = """\
SELECT id, username, password_hash, is_admin, disabled, must_change_password,
       failed_attempts, locked_until, created_at, updated_at, last_login_at,
       expires_at, pending_approval
FROM datasette_accounts_users
ORDER BY username;
"""
    params: dict[str, Any] = {}
    cursor = conn.execute(sql, params)
    return [UserRow(*row) for row in cursor.fetchall()]


def count_enabled_admins(conn: sqlite3.Connection) -> Any | None:
    sql = """\
SELECT COUNT(*) FROM datasette_accounts_users
WHERE is_admin = 1 AND disabled = 0 AND (expires_at IS NULL OR expires_at >
    strftime('%Y-%m-%dT%H:%M:%f','now') || '+00:00');
"""
    params: dict[str, Any] = {}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return row[0] if row is not None else None


def count_other_enabled_admins(conn: sqlite3.Connection, exclude_id: str) -> Any | None:
    sql = """\
SELECT COUNT(*) FROM datasette_accounts_users
WHERE is_admin = 1 AND disabled = 0 AND (expires_at IS NULL OR expires_at >
    strftime('%Y-%m-%dT%H:%M:%f','now') || '+00:00') AND id != $exclude_id::text;
"""
    params = {"exclude_id::text": exclude_id}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return row[0] if row is not None else None


def username_exists(conn: sqlite3.Connection, username: str) -> Any | None:
    sql = "SELECT 1 FROM datasette_accounts_users WHERE username = $username::text;"
    params = {"username::text": username}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return row[0] if row is not None else None


def user_id_exists(conn: sqlite3.Connection, user_id: str) -> Any | None:
    sql = "SELECT 1 FROM datasette_accounts_users WHERE id = $user_id::text;"
    params = {"user_id::text": user_id}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return row[0] if row is not None else None


def select_user_is_enabled_admin(conn: sqlite3.Connection, user_id: str) -> Any | None:
    sql = """\
SELECT is_admin = 1 AND disabled = 0 AND (expires_at IS NULL OR expires_at >
    strftime('%Y-%m-%dT%H:%M:%f','now') || '+00:00')
FROM datasette_accounts_users WHERE id = $user_id::text;
"""
    params = {"user_id::text": user_id}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return row[0] if row is not None else None


def select_user_admin_state(
    conn: sqlite3.Connection, user_id: str
) -> AdminStateRow | None:
    sql = "SELECT is_admin, disabled FROM datasette_accounts_users WHERE id = $user_id::text;"
    params = {"user_id::text": user_id}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return AdminStateRow(*row) if row is not None else None


def select_failed_attempts(conn: sqlite3.Connection, user_id: str) -> int | None:
    sql = "SELECT failed_attempts FROM datasette_accounts_users WHERE id = $user_id::text;"
    params = {"user_id::text": user_id}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return row[0] if row is not None else None


def insert_user(
    conn: sqlite3.Connection,
    id: str,
    username: str,
    password_hash: str,
    is_admin: int,
    must_change_password: int,
    pending_approval: int,
) -> None:
    sql = """\
INSERT INTO datasette_accounts_users
    (id, username, password_hash, is_admin, disabled, must_change_password,
     failed_attempts, locked_until, created_at, updated_at, pending_approval)
VALUES ($id::text, $username::text, $password_hash::text, $is_admin::integer, 0,
        $must_change_password::integer, 0, NULL,
        strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00',
        strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00',
        $pending_approval::integer);
"""
    params = {
        "id::text": id,
        "username::text": username,
        "password_hash::text": password_hash,
        "is_admin::integer": is_admin,
        "must_change_password::integer": must_change_password,
        "pending_approval::integer": pending_approval,
    }
    conn.execute(sql, params)
    return None


def bump_failed_attempts(conn: sqlite3.Connection, user_id: str) -> None:
    sql = """\
UPDATE datasette_accounts_users
SET failed_attempts = failed_attempts + 1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
WHERE id = $user_id::text;
"""
    params = {"user_id::text": user_id}
    conn.execute(sql, params)
    return None


def set_locked_until(
    conn: sqlite3.Connection, lockout_minutes: int, user_id: str
) -> None:
    sql = """\
UPDATE datasette_accounts_users
SET locked_until =
    strftime('%Y-%m-%dT%H:%M:%f', 'now', printf('%+d minutes', $lockout_minutes::integer))
    || '+00:00'
WHERE id = $user_id::text;
"""
    params = {"lockout_minutes::integer": lockout_minutes, "user_id::text": user_id}
    conn.execute(sql, params)
    return None


def clear_lockout(conn: sqlite3.Connection, user_id: str) -> None:
    sql = """\
UPDATE datasette_accounts_users
SET failed_attempts = 0, locked_until = NULL,
    updated_at = strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
WHERE id = $user_id::text;
"""
    params = {"user_id::text": user_id}
    conn.execute(sql, params)
    return None


def record_login_success(conn: sqlite3.Connection, user_id: str) -> None:
    sql = """\
UPDATE datasette_accounts_users
SET failed_attempts = 0, locked_until = NULL,
    last_login_at = strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00',
    updated_at = strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
WHERE id = $user_id::text;
"""
    params = {"user_id::text": user_id}
    conn.execute(sql, params)
    return None


def reset_password(conn: sqlite3.Connection, password_hash: str, user_id: str) -> None:
    sql = """\
UPDATE datasette_accounts_users
SET password_hash = $password_hash::text, must_change_password = 1,
    failed_attempts = 0, locked_until = NULL,
    updated_at = strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
WHERE id = $user_id::text;
"""
    params = {"password_hash::text": password_hash, "user_id::text": user_id}
    conn.execute(sql, params)
    return None


def change_own_password(
    conn: sqlite3.Connection, password_hash: str, user_id: str
) -> None:
    sql = """\
UPDATE datasette_accounts_users
SET password_hash = $password_hash::text, must_change_password = 0,
    failed_attempts = 0, locked_until = NULL,
    updated_at = strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
WHERE id = $user_id::text;
"""
    params = {"password_hash::text": password_hash, "user_id::text": user_id}
    conn.execute(sql, params)
    return None


def set_user_admin(conn: sqlite3.Connection, is_admin: int, user_id: str) -> None:
    sql = """\
UPDATE datasette_accounts_users
SET is_admin = $is_admin::integer,
    updated_at = strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
WHERE id = $user_id::text;
"""
    params = {"is_admin::integer": is_admin, "user_id::text": user_id}
    conn.execute(sql, params)
    return None


def set_user_disabled(conn: sqlite3.Connection, disabled: int, user_id: str) -> None:
    sql = """\
UPDATE datasette_accounts_users
SET disabled = $disabled::integer,
    updated_at = strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
WHERE id = $user_id::text;
"""
    params = {"disabled::integer": disabled, "user_id::text": user_id}
    conn.execute(sql, params)
    return None


def delete_user(conn: sqlite3.Connection, user_id: str) -> None:
    sql = "DELETE FROM datasette_accounts_users WHERE id = $user_id::text;"
    params = {"user_id::text": user_id}
    conn.execute(sql, params)
    return None


def set_user_approved(conn: sqlite3.Connection, user_id: str) -> None:
    sql = """\
UPDATE datasette_accounts_users
SET pending_approval = 0,
    updated_at = strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
WHERE id = $user_id::text;
"""
    params = {"user_id::text": user_id}
    conn.execute(sql, params)
    return None


def count_pending_users(conn: sqlite3.Connection) -> Any | None:
    sql = "SELECT COUNT(*) FROM datasette_accounts_users WHERE pending_approval = 1;"
    params: dict[str, Any] = {}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return row[0] if row is not None else None


def normalize_future_timestamp(conn: sqlite3.Connection, value: str) -> Any | None:
    sql = """\
SELECT CASE
    WHEN strftime('%Y-%m-%dT%H:%M:%f', $value::text) || '+00:00'
         > strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
    THEN strftime('%Y-%m-%dT%H:%M:%f', $value::text) || '+00:00'
END;
"""
    params = {"value::text": value}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return row[0] if row is not None else None


def expiry_in_days(conn: sqlite3.Connection, days: int) -> Any | None:
    sql = """\
SELECT strftime('%Y-%m-%dT%H:%M:%f', 'now', printf('%+d days', $days::integer))
       || '+00:00';
"""
    params = {"days::integer": days}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return row[0] if row is not None else None


def set_user_expiry(
    conn: sqlite3.Connection, expires_at: str | None, user_id: str
) -> None:
    sql = """\
UPDATE datasette_accounts_users
SET expires_at = $expires_at::text::,
    updated_at = strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
WHERE id = $user_id::text;
"""
    params = {"expires_at::text::": expires_at, "user_id::text": user_id}
    conn.execute(sql, params)
    return None


def select_session(conn: sqlite3.Connection, token_sha256: str) -> SessionRow | None:
    sql = """\
SELECT token_sha256, actor_id, created_at, expires_at, last_seen_at, user_agent, ip
FROM datasette_accounts_sessions
WHERE token_sha256 = $token_sha256::text;
"""
    params = {"token_sha256::text": token_sha256}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return SessionRow(*row) if row is not None else None


def list_sessions_for_user(conn: sqlite3.Connection, actor_id: str) -> list[SessionRow]:
    sql = """\
SELECT token_sha256, actor_id, created_at, expires_at, last_seen_at, user_agent, ip
FROM datasette_accounts_sessions
WHERE actor_id = $actor_id::text
ORDER BY last_seen_at DESC;
"""
    params = {"actor_id::text": actor_id}
    cursor = conn.execute(sql, params)
    return [SessionRow(*row) for row in cursor.fetchall()]


def insert_session(
    conn: sqlite3.Connection,
    token_sha256: str,
    actor_id: str,
    ttl_days: int,
    user_agent: str | None,
    ip: str | None,
    provider: str,
) -> None:
    sql = """\
INSERT INTO datasette_accounts_sessions
    (token_sha256, actor_id, created_at, expires_at, last_seen_at, user_agent, ip,
     provider)
VALUES ($token_sha256::text, $actor_id::text,
        strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00',
        strftime('%Y-%m-%dT%H:%M:%f', 'now', printf('%+d days', $ttl_days::integer))
        || '+00:00',
        strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00',
        $user_agent::text::, $ip::text::, $provider::text);
"""
    params = {
        "token_sha256::text": token_sha256,
        "actor_id::text": actor_id,
        "ttl_days::integer": ttl_days,
        "user_agent::text::": user_agent,
        "ip::text::": ip,
        "provider::text": provider,
    }
    conn.execute(sql, params)
    return None


def touch_last_seen(conn: sqlite3.Connection, token_sha256: str) -> None:
    sql = """\
UPDATE datasette_accounts_sessions
SET last_seen_at = strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
WHERE token_sha256 = $token_sha256::text;
"""
    params = {"token_sha256::text": token_sha256}
    conn.execute(sql, params)
    return None


def delete_session(conn: sqlite3.Connection, token_sha256: str) -> None:
    sql = "DELETE FROM datasette_accounts_sessions WHERE token_sha256 = $token_sha256::text;"
    params = {"token_sha256::text": token_sha256}
    conn.execute(sql, params)
    return None


def delete_session_for_actor(
    conn: sqlite3.Connection, token_sha256: str, actor_id: str
) -> None:
    sql = """\
DELETE FROM datasette_accounts_sessions
WHERE token_sha256 = $token_sha256::text AND actor_id = $actor_id::text;
"""
    params = {"token_sha256::text": token_sha256, "actor_id::text": actor_id}
    conn.execute(sql, params)
    return None


def delete_sessions_for_actor(conn: sqlite3.Connection, actor_id: str) -> None:
    sql = "DELETE FROM datasette_accounts_sessions WHERE actor_id = $actor_id::text;"
    params = {"actor_id::text": actor_id}
    conn.execute(sql, params)
    return None


def delete_other_sessions_for_actor(
    conn: sqlite3.Connection, actor_id: str, token_sha256: str
) -> None:
    sql = """\
DELETE FROM datasette_accounts_sessions
WHERE actor_id = $actor_id::text AND token_sha256 != $token_sha256::text;
"""
    params = {"actor_id::text": actor_id, "token_sha256::text": token_sha256}
    conn.execute(sql, params)
    return None


def delete_expired_sessions(conn: sqlite3.Connection) -> None:
    sql = """\
DELETE FROM datasette_accounts_sessions
WHERE expires_at <= strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00';
"""
    params: dict[str, Any] = {}
    conn.execute(sql, params)
    return None


def select_identity(
    conn: sqlite3.Connection, provider: str, subject: str
) -> IdentityRow | None:
    sql = """\
SELECT provider, subject, user_id, email, display_name, created_at, last_login_at
FROM datasette_accounts_identities
WHERE provider = $provider::text AND subject = $subject::text;
"""
    params = {"provider::text": provider, "subject::text": subject}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return IdentityRow(*row) if row is not None else None


def list_identities_for_user(
    conn: sqlite3.Connection, user_id: str
) -> list[IdentityRow]:
    sql = """\
SELECT provider, subject, user_id, email, display_name, created_at, last_login_at
FROM datasette_accounts_identities
WHERE user_id = $user_id::text
ORDER BY created_at;
"""
    params = {"user_id::text": user_id}
    cursor = conn.execute(sql, params)
    return [IdentityRow(*row) for row in cursor.fetchall()]


def count_identities_for_user(conn: sqlite3.Connection, user_id: str) -> Any | None:
    sql = "SELECT COUNT(*) FROM datasette_accounts_identities WHERE user_id = $user_id::text;"
    params = {"user_id::text": user_id}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return row[0] if row is not None else None


def count_identities_by_provider(
    conn: sqlite3.Connection,
) -> list[CountIdentitiesByProviderRow]:
    sql = """\
SELECT provider, COUNT(*) AS n
FROM datasette_accounts_identities
GROUP BY provider;
"""
    params: dict[str, Any] = {}
    cursor = conn.execute(sql, params)
    return [CountIdentitiesByProviderRow(*row) for row in cursor.fetchall()]


def insert_identity(
    conn: sqlite3.Connection,
    provider: str,
    subject: str,
    user_id: str,
    email: str | None,
    display_name: str | None,
) -> None:
    sql = """\
INSERT INTO datasette_accounts_identities
    (provider, subject, user_id, email, display_name, created_at, last_login_at)
VALUES ($provider::text, $subject::text, $user_id::text,
        $email::text::, $display_name::text::,
        strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00', NULL);
"""
    params = {
        "provider::text": provider,
        "subject::text": subject,
        "user_id::text": user_id,
        "email::text::": email,
        "display_name::text::": display_name,
    }
    conn.execute(sql, params)
    return None


def touch_identity_last_login(
    conn: sqlite3.Connection, provider: str, subject: str
) -> None:
    sql = """\
UPDATE datasette_accounts_identities
SET last_login_at = strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
WHERE provider = $provider::text AND subject = $subject::text;
"""
    params = {"provider::text": provider, "subject::text": subject}
    conn.execute(sql, params)
    return None


def delete_identity(conn: sqlite3.Connection, provider: str, subject: str) -> None:
    sql = """\
DELETE FROM datasette_accounts_identities
WHERE provider = $provider::text AND subject = $subject::text;
"""
    params = {"provider::text": provider, "subject::text": subject}
    conn.execute(sql, params)
    return None


def delete_identities_for_user(conn: sqlite3.Connection, user_id: str) -> None:
    sql = "DELETE FROM datasette_accounts_identities WHERE user_id = $user_id::text;"
    params = {"user_id::text": user_id}
    conn.execute(sql, params)
    return None


def insert_login_attempt(
    conn: sqlite3.Connection,
    username: str | None,
    ip: str | None,
    success: int,
    reason: str | None,
    provider: str | None,
) -> None:
    sql = """\
INSERT INTO datasette_accounts_login_audit
    (username, ip, timestamp, success, reason, provider)
VALUES ($username::text::, $ip::text::,
        strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00',
        $success::integer, $reason::text::, $provider::text::);
"""
    params = {
        "username::text::": username,
        "ip::text::": ip,
        "success::integer": success,
        "reason::text::": reason,
        "provider::text::": provider,
    }
    conn.execute(sql, params)
    return None


def list_login_attempts(
    conn: sqlite3.Connection, username: str | None, ip: str | None, limit: int
) -> list[LoginAttemptRow]:
    sql = """\
SELECT id, username, ip, timestamp, success, reason
FROM datasette_accounts_login_audit
WHERE ($username::text:: IS NULL OR username = $username::text::)
  AND ($ip::text:: IS NULL OR ip = $ip::text::)
ORDER BY id DESC
LIMIT $limit::integer;
"""
    params = {"username::text::": username, "ip::text::": ip, "limit::integer": limit}
    cursor = conn.execute(sql, params)
    return [LoginAttemptRow(*row) for row in cursor.fetchall()]


def count_recent_registrations(conn: sqlite3.Connection, ip: str) -> Any | None:
    sql = """\
SELECT COUNT(*) FROM datasette_accounts_login_audit
WHERE ip = $ip::text AND reason = 'register'
  AND timestamp > strftime('%Y-%m-%dT%H:%M:%f', 'now', '-1 day') || '+00:00';
"""
    params = {"ip::text": ip}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return row[0] if row is not None else None


def purge_login_audit(conn: sqlite3.Connection, retention_days: int) -> None:
    sql = """\
DELETE FROM datasette_accounts_login_audit
WHERE timestamp <
    strftime('%Y-%m-%dT%H:%M:%f', 'now', printf('-%d days', $retention_days::integer))
    || '+00:00';
"""
    params = {"retention_days::integer": retention_days}
    conn.execute(sql, params)
    return None


def insert_admin_audit(
    conn: sqlite3.Connection,
    operation: str,
    actor_id: str | None,
    target_id: str | None,
    detail: str | None,
) -> None:
    sql = """\
INSERT INTO datasette_accounts_admin_audit
    (timestamp, operation, actor_id, target_id, detail)
VALUES (strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00',
        $operation::text, $actor_id::text::, $target_id::text::, $detail::text::);
"""
    params = {
        "operation::text": operation,
        "actor_id::text::": actor_id,
        "target_id::text::": target_id,
        "detail::text::": detail,
    }
    conn.execute(sql, params)
    return None


def list_admin_audit(
    conn: sqlite3.Connection, target_id: str | None, operation: str | None, limit: int
) -> list[AdminAuditRow]:
    sql = """\
SELECT a.id, a.timestamp, a.operation, a.actor_id, a.target_id, a.detail,
       (SELECT username FROM datasette_accounts_users WHERE id = a.actor_id)
           AS actor_username,
       (SELECT username FROM datasette_accounts_users WHERE id = a.target_id)
           AS target_username
FROM datasette_accounts_admin_audit a
WHERE ($target_id::text:: IS NULL OR a.target_id = $target_id::text::)
  AND ($operation::text:: IS NULL OR a.operation = $operation::text::)
ORDER BY a.id DESC
LIMIT $limit::integer;
"""
    params = {
        "target_id::text::": target_id,
        "operation::text::": operation,
        "limit::integer": limit,
    }
    cursor = conn.execute(sql, params)
    return [AdminAuditRow(*row) for row in cursor.fetchall()]


def list_admin_audit_operations(
    conn: sqlite3.Connection,
) -> list[ListAdminAuditOperationsRow]:
    sql = "SELECT DISTINCT operation FROM datasette_accounts_admin_audit ORDER BY 1;"
    params: dict[str, Any] = {}
    cursor = conn.execute(sql, params)
    return [ListAdminAuditOperationsRow(*row) for row in cursor.fetchall()]


def purge_admin_audit(conn: sqlite3.Connection, retention_days: int) -> None:
    sql = """\
DELETE FROM datasette_accounts_admin_audit
WHERE timestamp <
    strftime('%Y-%m-%dT%H:%M:%f', 'now', printf('-%d days', $retention_days::integer))
    || '+00:00';
"""
    params = {"retention_days::integer": retention_days}
    conn.execute(sql, params)
    return None


def insert_capability_grant(
    conn: sqlite3.Connection,
    action: str,
    principal_type: str,
    actor_id: str | None,
    group_id: int | None,
    created_by: str | None,
) -> int | None:
    sql = """\
INSERT OR IGNORE INTO datasette_accounts_capability_grants
    (action, principal_type, actor_id, group_id, created_at, created_by)
VALUES ($action::text, $principal_type::text, $actor_id::text::, $group_id::integer::,
        strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00', $created_by::text::)
RETURNING id;
"""
    params = {
        "action::text": action,
        "principal_type::text": principal_type,
        "actor_id::text::": actor_id,
        "group_id::integer::": group_id,
        "created_by::text::": created_by,
    }
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return row[0] if row is not None else None


def select_capability_grant(
    conn: sqlite3.Connection, grant_id: int
) -> CapabilityGrantRow | None:
    sql = """\
SELECT action, principal_type, actor_id, group_id
FROM datasette_accounts_capability_grants
WHERE id = $grant_id::integer;
"""
    params = {"grant_id::integer": grant_id}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return CapabilityGrantRow(*row) if row is not None else None


def delete_capability_grant(conn: sqlite3.Connection, grant_id: int) -> None:
    sql = "DELETE FROM datasette_accounts_capability_grants WHERE id = $grant_id::integer;"
    params = {"grant_id::integer": grant_id}
    conn.execute(sql, params)
    return None


def list_site_messages(conn: sqlite3.Connection) -> list[SiteMessageRow]:
    sql = "SELECT key, body FROM datasette_accounts_site_messages;"
    params: dict[str, Any] = {}
    cursor = conn.execute(sql, params)
    return [SiteMessageRow(*row) for row in cursor.fetchall()]


def select_site_message(conn: sqlite3.Connection, key: str) -> str | None:
    sql = "SELECT body FROM datasette_accounts_site_messages WHERE key = $key::text;"
    params = {"key::text": key}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return row[0] if row is not None else None


def upsert_site_message(
    conn: sqlite3.Connection, key: str, body: str, updated_by: str | None
) -> None:
    sql = """\
INSERT INTO datasette_accounts_site_messages (key, body, updated_at, updated_by)
VALUES ($key::text, $body::text,
        strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00', $updated_by::text::)
ON CONFLICT(key) DO UPDATE SET
    body = excluded.body, updated_at = excluded.updated_at,
    updated_by = excluded.updated_by;
"""
    params = {"key::text": key, "body::text": body, "updated_by::text::": updated_by}
    conn.execute(sql, params)
    return None


def delete_site_message(conn: sqlite3.Connection, key: str) -> str | None:
    sql = "DELETE FROM datasette_accounts_site_messages WHERE key = $key::text RETURNING key;"
    params = {"key::text": key}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return row[0] if row is not None else None


def select_setting(conn: sqlite3.Connection, key: str) -> str | None:
    sql = "SELECT value FROM datasette_accounts_settings WHERE key = $key::text;"
    params = {"key::text": key}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return row[0] if row is not None else None


def upsert_setting(
    conn: sqlite3.Connection, key: str, value: str, updated_by: str | None
) -> None:
    sql = """\
INSERT INTO datasette_accounts_settings (key, value, updated_at, updated_by)
VALUES ($key::text, $value::text,
        strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00', $updated_by::text::)
ON CONFLICT(key) DO UPDATE SET
    value = excluded.value, updated_at = excluded.updated_at,
    updated_by = excluded.updated_by;
"""
    params = {"key::text": key, "value::text": value, "updated_by::text::": updated_by}
    conn.execute(sql, params)
    return None


def delete_setting(conn: sqlite3.Connection, key: str) -> None:
    sql = "DELETE FROM datasette_accounts_settings WHERE key = $key::text;"
    params = {"key::text": key}
    conn.execute(sql, params)
    return None


def insert_password_token(
    conn: sqlite3.Connection,
    token_sha256: str,
    user_id: str,
    purpose: str,
    ttl_hours: int,
    created_by: str | None,
) -> None:
    sql = """\
INSERT INTO datasette_accounts_password_tokens
    (token_sha256, user_id, purpose, created_at, expires_at, created_by)
VALUES ($token_sha256::text, $user_id::text, $purpose::text,
        strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00',
        strftime('%Y-%m-%dT%H:%M:%f', 'now', printf('%+d hours', $ttl_hours::integer))
        || '+00:00',
        $created_by::text::);
"""
    params = {
        "token_sha256::text": token_sha256,
        "user_id::text": user_id,
        "purpose::text": purpose,
        "ttl_hours::integer": ttl_hours,
        "created_by::text::": created_by,
    }
    conn.execute(sql, params)
    return None


def select_password_token(
    conn: sqlite3.Connection, token_sha256: str
) -> PasswordTokenRow | None:
    sql = """\
SELECT t.token_sha256, t.user_id, t.purpose, t.created_at, t.expires_at,
       t.created_by, u.username
FROM datasette_accounts_password_tokens t
JOIN datasette_accounts_users u ON u.id = t.user_id
WHERE t.token_sha256 = $token_sha256::text
  AND t.expires_at > strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00';
"""
    params = {"token_sha256::text": token_sha256}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return PasswordTokenRow(*row) if row is not None else None


def delete_password_token(conn: sqlite3.Connection, token_sha256: str) -> str | None:
    sql = """\
DELETE FROM datasette_accounts_password_tokens
WHERE token_sha256 = $token_sha256::text
  AND expires_at > strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
RETURNING user_id;
"""
    params = {"token_sha256::text": token_sha256}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return row[0] if row is not None else None


def delete_password_tokens_for_user(conn: sqlite3.Connection, user_id: str) -> None:
    sql = (
        "DELETE FROM datasette_accounts_password_tokens WHERE user_id = $user_id::text;"
    )
    params = {"user_id::text": user_id}
    conn.execute(sql, params)
    return None


def purge_expired_password_tokens(conn: sqlite3.Connection) -> None:
    sql = """\
DELETE FROM datasette_accounts_password_tokens
WHERE purpose = 'reset'
  AND expires_at <= strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00';
"""
    params: dict[str, Any] = {}
    conn.execute(sql, params)
    return None


def list_password_token_meta(conn: sqlite3.Connection) -> list[PasswordTokenMetaRow]:
    sql = """\
SELECT t.user_id, t.purpose, t.created_at, t.expires_at, t.created_by,
       cu.username AS created_by_username
FROM datasette_accounts_password_tokens t
LEFT JOIN datasette_accounts_users cu ON cu.id = t.created_by
WHERE t.purpose = 'invite'
   OR t.expires_at > strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00';
"""
    params: dict[str, Any] = {}
    cursor = conn.execute(sql, params)
    return [PasswordTokenMetaRow(*row) for row in cursor.fetchall()]


def set_password_from_token(
    conn: sqlite3.Connection, password_hash: str, user_id: str
) -> None:
    sql = """\
UPDATE datasette_accounts_users
SET password_hash = $password_hash::text, must_change_password = 0,
    updated_at = strftime('%Y-%m-%dT%H:%M:%f', 'now') || '+00:00'
WHERE id = $user_id::text;
"""
    params = {"password_hash::text": password_hash, "user_id::text": user_id}
    conn.execute(sql, params)
    return None
