"""AUTOGENERATED by tools/gen_queries.py — do not edit.

This file is generated from datasette_accounts/sql/queries.sql.
Regenerate with `just codegen-queries` after editing that file.
"""

from __future__ import annotations

import sqlite3
from dataclasses import dataclass
from typing import Any


@dataclass
class UserRow:
    id: str | None
    username: str
    password_hash: str
    is_admin: int
    disabled: int
    must_change_password: int
    failed_attempts: int
    locked_until: str | None
    created_at: str
    updated_at: str
    last_login_at: str | None


@dataclass
class AdminStateRow:
    is_admin: int
    disabled: int


@dataclass
class SessionRow:
    token_sha256: str | None
    actor_id: str
    created_at: str
    expires_at: str
    last_seen_at: str
    user_agent: str | None
    ip: str | None


@dataclass
class LoginAttemptRow:
    id: int | None
    username: str | None
    ip: str | None
    timestamp: str
    success: int
    reason: str | None


@dataclass
class CapabilityGrantRow:
    action: str
    principal_type: str
    actor_id: str | None
    group_id: int | None


@dataclass
class SiteMessageRow:
    key: str | None
    body: str


def select_user_by_username(conn: sqlite3.Connection, username: str) -> UserRow | None:
    sql = """\
SELECT id, username, password_hash, is_admin, disabled, must_change_password,
       failed_attempts, locked_until, created_at, updated_at, last_login_at
FROM datasette_accounts_users
WHERE username = $username::text;
"""
    params = {"username::text": username}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return UserRow(*row) if row is not None else None


def select_user_by_id(conn: sqlite3.Connection, user_id: str) -> UserRow | None:
    sql = """\
SELECT id, username, password_hash, is_admin, disabled, must_change_password,
       failed_attempts, locked_until, created_at, updated_at, last_login_at
FROM datasette_accounts_users
WHERE id = $user_id::text;
"""
    params = {"user_id::text": user_id}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return UserRow(*row) if row is not None else None


def list_users(conn: sqlite3.Connection) -> list[UserRow]:
    sql = """\
SELECT id, username, password_hash, is_admin, disabled, must_change_password,
       failed_attempts, locked_until, created_at, updated_at, last_login_at
FROM datasette_accounts_users
ORDER BY username;
"""
    params: dict[str, Any] = {}
    cursor = conn.execute(sql, params)
    return [UserRow(*row) for row in cursor.fetchall()]


def count_enabled_admins(conn: sqlite3.Connection) -> Any | None:
    sql = """\
SELECT COUNT(*) FROM datasette_accounts_users
WHERE is_admin = 1 AND disabled = 0;
"""
    params: dict[str, Any] = {}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return row[0] if row is not None else None


def count_other_enabled_admins(conn: sqlite3.Connection, exclude_id: str) -> Any | None:
    sql = """\
SELECT COUNT(*) FROM datasette_accounts_users
WHERE is_admin = 1 AND disabled = 0 AND id != $exclude_id::text;
"""
    params = {"exclude_id::text": exclude_id}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return row[0] if row is not None else None


def username_exists(conn: sqlite3.Connection, username: str) -> Any | None:
    sql = "SELECT 1 FROM datasette_accounts_users WHERE username = $username::text;"
    params = {"username::text": username}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return row[0] if row is not None else None


def user_id_exists(conn: sqlite3.Connection, user_id: str) -> Any | None:
    sql = "SELECT 1 FROM datasette_accounts_users WHERE id = $user_id::text;"
    params = {"user_id::text": user_id}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return row[0] if row is not None else None


def select_user_is_enabled_admin(conn: sqlite3.Connection, user_id: str) -> Any | None:
    sql = """\
SELECT is_admin = 1 AND disabled = 0
FROM datasette_accounts_users WHERE id = $user_id::text;
"""
    params = {"user_id::text": user_id}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return row[0] if row is not None else None


def select_user_admin_state(
    conn: sqlite3.Connection, user_id: str
) -> AdminStateRow | None:
    sql = "SELECT is_admin, disabled FROM datasette_accounts_users WHERE id = $user_id::text;"
    params = {"user_id::text": user_id}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return AdminStateRow(*row) if row is not None else None


def select_failed_attempts(conn: sqlite3.Connection, user_id: str) -> int | None:
    sql = "SELECT failed_attempts FROM datasette_accounts_users WHERE id = $user_id::text;"
    params = {"user_id::text": user_id}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return row[0] if row is not None else None


def insert_user(
    conn: sqlite3.Connection,
    id: str,
    username: str,
    password_hash: str,
    is_admin: int,
    must_change_password: int,
    created_at: str,
    updated_at: str,
) -> None:
    sql = """\
INSERT INTO datasette_accounts_users
    (id, username, password_hash, is_admin, disabled, must_change_password,
     failed_attempts, locked_until, created_at, updated_at)
VALUES ($id::text, $username::text, $password_hash::text, $is_admin::integer, 0,
        $must_change_password::integer, 0, NULL, $created_at::text, $updated_at::text);
"""
    params = {
        "id::text": id,
        "username::text": username,
        "password_hash::text": password_hash,
        "is_admin::integer": is_admin,
        "must_change_password::integer": must_change_password,
        "created_at::text": created_at,
        "updated_at::text": updated_at,
    }
    conn.execute(sql, params)
    return None


def bump_failed_attempts(
    conn: sqlite3.Connection, updated_at: str, user_id: str
) -> None:
    sql = """\
UPDATE datasette_accounts_users
SET failed_attempts = failed_attempts + 1, updated_at = $updated_at::text
WHERE id = $user_id::text;
"""
    params = {"updated_at::text": updated_at, "user_id::text": user_id}
    conn.execute(sql, params)
    return None


def set_locked_until(conn: sqlite3.Connection, locked_until: str, user_id: str) -> None:
    sql = """\
UPDATE datasette_accounts_users
SET locked_until = $locked_until::text WHERE id = $user_id::text;
"""
    params = {"locked_until::text": locked_until, "user_id::text": user_id}
    conn.execute(sql, params)
    return None


def clear_lockout(conn: sqlite3.Connection, updated_at: str, user_id: str) -> None:
    sql = """\
UPDATE datasette_accounts_users
SET failed_attempts = 0, locked_until = NULL, updated_at = $updated_at::text
WHERE id = $user_id::text;
"""
    params = {"updated_at::text": updated_at, "user_id::text": user_id}
    conn.execute(sql, params)
    return None


def record_login_success(
    conn: sqlite3.Connection, timestamp: str, user_id: str
) -> None:
    sql = """\
UPDATE datasette_accounts_users
SET failed_attempts = 0, locked_until = NULL,
    last_login_at = $timestamp::text, updated_at = $timestamp::text
WHERE id = $user_id::text;
"""
    params = {"timestamp::text": timestamp, "user_id::text": user_id}
    conn.execute(sql, params)
    return None


def reset_password(
    conn: sqlite3.Connection, password_hash: str, updated_at: str, user_id: str
) -> None:
    sql = """\
UPDATE datasette_accounts_users
SET password_hash = $password_hash::text, must_change_password = 1,
    failed_attempts = 0, locked_until = NULL, updated_at = $updated_at::text
WHERE id = $user_id::text;
"""
    params = {
        "password_hash::text": password_hash,
        "updated_at::text": updated_at,
        "user_id::text": user_id,
    }
    conn.execute(sql, params)
    return None


def change_own_password(
    conn: sqlite3.Connection, password_hash: str, updated_at: str, user_id: str
) -> None:
    sql = """\
UPDATE datasette_accounts_users
SET password_hash = $password_hash::text, must_change_password = 0,
    failed_attempts = 0, locked_until = NULL, updated_at = $updated_at::text
WHERE id = $user_id::text;
"""
    params = {
        "password_hash::text": password_hash,
        "updated_at::text": updated_at,
        "user_id::text": user_id,
    }
    conn.execute(sql, params)
    return None


def set_user_admin(
    conn: sqlite3.Connection, is_admin: int, updated_at: str, user_id: str
) -> None:
    sql = """\
UPDATE datasette_accounts_users
SET is_admin = $is_admin::integer, updated_at = $updated_at::text
WHERE id = $user_id::text;
"""
    params = {
        "is_admin::integer": is_admin,
        "updated_at::text": updated_at,
        "user_id::text": user_id,
    }
    conn.execute(sql, params)
    return None


def set_user_disabled(
    conn: sqlite3.Connection, disabled: int, updated_at: str, user_id: str
) -> None:
    sql = """\
UPDATE datasette_accounts_users
SET disabled = $disabled::integer, updated_at = $updated_at::text
WHERE id = $user_id::text;
"""
    params = {
        "disabled::integer": disabled,
        "updated_at::text": updated_at,
        "user_id::text": user_id,
    }
    conn.execute(sql, params)
    return None


def delete_user(conn: sqlite3.Connection, user_id: str) -> None:
    sql = "DELETE FROM datasette_accounts_users WHERE id = $user_id::text;"
    params = {"user_id::text": user_id}
    conn.execute(sql, params)
    return None


def select_session(conn: sqlite3.Connection, token_sha256: str) -> SessionRow | None:
    sql = """\
SELECT token_sha256, actor_id, created_at, expires_at, last_seen_at, user_agent, ip
FROM datasette_accounts_sessions
WHERE token_sha256 = $token_sha256::text;
"""
    params = {"token_sha256::text": token_sha256}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return SessionRow(*row) if row is not None else None


def list_sessions_for_user(conn: sqlite3.Connection, actor_id: str) -> list[SessionRow]:
    sql = """\
SELECT token_sha256, actor_id, created_at, expires_at, last_seen_at, user_agent, ip
FROM datasette_accounts_sessions
WHERE actor_id = $actor_id::text
ORDER BY last_seen_at DESC;
"""
    params = {"actor_id::text": actor_id}
    cursor = conn.execute(sql, params)
    return [SessionRow(*row) for row in cursor.fetchall()]


def insert_session(
    conn: sqlite3.Connection,
    token_sha256: str,
    actor_id: str,
    created_at: str,
    expires_at: str,
    last_seen_at: str,
    user_agent: str | None,
    ip: str | None,
) -> None:
    sql = """\
INSERT INTO datasette_accounts_sessions
    (token_sha256, actor_id, created_at, expires_at, last_seen_at, user_agent, ip)
VALUES ($token_sha256::text, $actor_id::text, $created_at::text, $expires_at::text,
        $last_seen_at::text, $user_agent::text::, $ip::text::);
"""
    params = {
        "token_sha256::text": token_sha256,
        "actor_id::text": actor_id,
        "created_at::text": created_at,
        "expires_at::text": expires_at,
        "last_seen_at::text": last_seen_at,
        "user_agent::text::": user_agent,
        "ip::text::": ip,
    }
    conn.execute(sql, params)
    return None


def touch_last_seen(
    conn: sqlite3.Connection, last_seen_at: str, token_sha256: str
) -> None:
    sql = """\
UPDATE datasette_accounts_sessions
SET last_seen_at = $last_seen_at::text WHERE token_sha256 = $token_sha256::text;
"""
    params = {"last_seen_at::text": last_seen_at, "token_sha256::text": token_sha256}
    conn.execute(sql, params)
    return None


def delete_session(conn: sqlite3.Connection, token_sha256: str) -> None:
    sql = "DELETE FROM datasette_accounts_sessions WHERE token_sha256 = $token_sha256::text;"
    params = {"token_sha256::text": token_sha256}
    conn.execute(sql, params)
    return None


def delete_session_for_actor(
    conn: sqlite3.Connection, token_sha256: str, actor_id: str
) -> None:
    sql = """\
DELETE FROM datasette_accounts_sessions
WHERE token_sha256 = $token_sha256::text AND actor_id = $actor_id::text;
"""
    params = {"token_sha256::text": token_sha256, "actor_id::text": actor_id}
    conn.execute(sql, params)
    return None


def delete_sessions_for_actor(conn: sqlite3.Connection, actor_id: str) -> None:
    sql = "DELETE FROM datasette_accounts_sessions WHERE actor_id = $actor_id::text;"
    params = {"actor_id::text": actor_id}
    conn.execute(sql, params)
    return None


def delete_other_sessions_for_actor(
    conn: sqlite3.Connection, actor_id: str, token_sha256: str
) -> None:
    sql = """\
DELETE FROM datasette_accounts_sessions
WHERE actor_id = $actor_id::text AND token_sha256 != $token_sha256::text;
"""
    params = {"actor_id::text": actor_id, "token_sha256::text": token_sha256}
    conn.execute(sql, params)
    return None


def delete_expired_sessions(conn: sqlite3.Connection, now: str) -> None:
    sql = "DELETE FROM datasette_accounts_sessions WHERE expires_at <= $now::text;"
    params = {"now::text": now}
    conn.execute(sql, params)
    return None


def insert_login_attempt(
    conn: sqlite3.Connection,
    username: str | None,
    ip: str | None,
    timestamp: str,
    success: int,
    reason: str | None,
) -> None:
    sql = """\
INSERT INTO datasette_accounts_login_audit (username, ip, timestamp, success, reason)
VALUES ($username::text::, $ip::text::, $timestamp::text, $success::integer,
        $reason::text::);
"""
    params = {
        "username::text::": username,
        "ip::text::": ip,
        "timestamp::text": timestamp,
        "success::integer": success,
        "reason::text::": reason,
    }
    conn.execute(sql, params)
    return None


def list_login_attempts(
    conn: sqlite3.Connection, username: str | None, ip: str | None, limit: int
) -> list[LoginAttemptRow]:
    sql = """\
SELECT id, username, ip, timestamp, success, reason
FROM datasette_accounts_login_audit
WHERE ($username::text:: IS NULL OR username = $username::text::)
  AND ($ip::text:: IS NULL OR ip = $ip::text::)
ORDER BY id DESC
LIMIT $limit::integer;
"""
    params = {"username::text::": username, "ip::text::": ip, "limit::integer": limit}
    cursor = conn.execute(sql, params)
    return [LoginAttemptRow(*row) for row in cursor.fetchall()]


def purge_login_audit(conn: sqlite3.Connection, cutoff: str) -> None:
    sql = "DELETE FROM datasette_accounts_login_audit WHERE timestamp < $cutoff::text;"
    params = {"cutoff::text": cutoff}
    conn.execute(sql, params)
    return None


def insert_admin_audit(
    conn: sqlite3.Connection,
    timestamp: str,
    operation: str,
    actor_id: str | None,
    target_id: str | None,
    detail: str | None,
) -> None:
    sql = """\
INSERT INTO datasette_accounts_admin_audit
    (timestamp, operation, actor_id, target_id, detail)
VALUES ($timestamp::text, $operation::text, $actor_id::text::, $target_id::text::,
        $detail::text::);
"""
    params = {
        "timestamp::text": timestamp,
        "operation::text": operation,
        "actor_id::text::": actor_id,
        "target_id::text::": target_id,
        "detail::text::": detail,
    }
    conn.execute(sql, params)
    return None


def insert_capability_grant(
    conn: sqlite3.Connection,
    action: str,
    principal_type: str,
    actor_id: str | None,
    group_id: int | None,
    created_at: str,
    created_by: str | None,
) -> int | None:
    sql = """\
INSERT OR IGNORE INTO datasette_accounts_capability_grants
    (action, principal_type, actor_id, group_id, created_at, created_by)
VALUES ($action::text, $principal_type::text, $actor_id::text::, $group_id::integer::,
        $created_at::text, $created_by::text::)
RETURNING id;
"""
    params = {
        "action::text": action,
        "principal_type::text": principal_type,
        "actor_id::text::": actor_id,
        "group_id::integer::": group_id,
        "created_at::text": created_at,
        "created_by::text::": created_by,
    }
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return row[0] if row is not None else None


def select_capability_grant(
    conn: sqlite3.Connection, grant_id: int
) -> CapabilityGrantRow | None:
    sql = """\
SELECT action, principal_type, actor_id, group_id
FROM datasette_accounts_capability_grants
WHERE id = $grant_id::integer;
"""
    params = {"grant_id::integer": grant_id}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return CapabilityGrantRow(*row) if row is not None else None


def delete_capability_grant(conn: sqlite3.Connection, grant_id: int) -> None:
    sql = "DELETE FROM datasette_accounts_capability_grants WHERE id = $grant_id::integer;"
    params = {"grant_id::integer": grant_id}
    conn.execute(sql, params)
    return None


def list_site_messages(conn: sqlite3.Connection) -> list[SiteMessageRow]:
    sql = "SELECT key, body FROM datasette_accounts_site_messages;"
    params: dict[str, Any] = {}
    cursor = conn.execute(sql, params)
    return [SiteMessageRow(*row) for row in cursor.fetchall()]


def select_site_message(conn: sqlite3.Connection, key: str) -> str | None:
    sql = "SELECT body FROM datasette_accounts_site_messages WHERE key = $key::text;"
    params = {"key::text": key}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return row[0] if row is not None else None


def upsert_site_message(
    conn: sqlite3.Connection,
    key: str,
    body: str,
    updated_at: str,
    updated_by: str | None,
) -> None:
    sql = """\
INSERT INTO datasette_accounts_site_messages (key, body, updated_at, updated_by)
VALUES ($key::text, $body::text, $updated_at::text, $updated_by::text::)
ON CONFLICT(key) DO UPDATE SET
    body = excluded.body, updated_at = excluded.updated_at,
    updated_by = excluded.updated_by;
"""
    params = {
        "key::text": key,
        "body::text": body,
        "updated_at::text": updated_at,
        "updated_by::text::": updated_by,
    }
    conn.execute(sql, params)
    return None


def delete_site_message(conn: sqlite3.Connection, key: str) -> str | None:
    sql = "DELETE FROM datasette_accounts_site_messages WHERE key = $key::text RETURNING key;"
    params = {"key::text": key}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return row[0] if row is not None else None
